# Generated by Django 5.2.9 on 2025-12-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setpoint', models.FloatField(default=50.0)),
            ],
            options={
                'verbose_name': 'Configuração',
                'verbose_name_plural': 'Configurações',
            },
        ),
        migrations.CreateModel(
            name='Telemetria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('umidade', models.FloatField()),
                ('setpoint', models.FloatField()),
                ('sistema_ativo', models.BooleanField(default=False)),
                ('atuando', models.BooleanField(default=False)),
                ('nivel_agua_baixo', models.BooleanField(default=False)),
                ('violacao_geral', models.BooleanField(default=False)),
                ('alarme', models.BooleanField(default=False)),
            ],
        ),
    ]
